### ISSUE TITLE
Create Start Screen.

### ISSUE THREAD

**Issue by abhinavk454** [abhinavk454/PaperFootball#2]
Create Start screen and use paper color pallets.

**Comment by abhinavk454** [comment]
![evil](https://user-images.githubusercontent.com/32016468/216242509-4a1582ba-0a84-4cb5-adf9-4ad07aa55ef6.png)

**Comment by abhinavk454** [comment]
@abhinavat2nd send me grayscale version

**Comment by abhinavat2nd** [comment]
![216242509-4a1582ba-0a84-4cb5-adf9-4ad07aa55ef6](https://user-images.githubusercontent.com/124233671/216243708-3fb25321-8f04-4b8b-9f53-ecab238f6938.png)
@abhinavk454
