### ISSUE TITLE
Add Music to start screen

### ISSUE THREAD

**Issue by abhinavk454** [abhinavk454/PaperFootball#8]
- [x] Select proper music of slight old one
- [x] Do testing properly both with headphone and speaker
- [x] Music should loop after some time

**Comment by abhinavk454** [comment]
@abhinavat2nd please send me music file

**Comment by abhinavat2nd** [comment]
> @abhinavat2nd please send me music file

how muh long

**Comment by abhinavk454** [comment]
> > @abhinavat2nd please send me music file
> 
> how much long
10

**Comment by abhinavat2nd** [comment]
[start.zip](https://github.com/abhinavk454/PaperFootball/files/10577375/start.zip)

**Comment by abhinavat2nd** [comment]
Just add on off features in sound tab
